function tab = iden(sign,unite)

    
    %type de message
    A = ~[...
        [ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite)] ];
    B = ~[...
        [ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite)];...
        [ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite)] ];
    C = ~[...
        [zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite)];...
        [zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite)];...
        [zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite)];...
        [zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite)];...
        [zeros(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite)];...
        [zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite)];...
        [zeros(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),ones(1,unite)];...
        [zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite)];...
        [zeros(1,unite),ones(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite),ones(1,unite)];...
        [zeros(1,unite),zeros(1,unite),zeros(1,unite),ones(1,unite),zeros(1,unite),ones(1,unite),ones(1,unite)] ];
        
    %tableau de determination du premier chiffre
    premier = [...
        [0,0,0,0,0,0];...
        [0,0,1,0,1,1];...
        [0,0,1,1,0,1];...
        [0,0,1,1,1,0];...
        [0,1,0,0,1,1];...
        [0,1,1,0,0,1];...
        [0,1,1,1,0,0];...
        [0,1,0,1,0,1];...
        [0,1,0,1,1,0];...
        [0,1,1,0,1,0] ];
    
        
    sign_garde = sign(3*unite+1:end-3*unite); %On enlève les gardes des bords
    tab = zeros(13,1); % tableau de nombre du code barre
    famille = zeros(1,6); % familles des chiffres 2 a 6
    
    for i = 1:6
        minval = 999;
        minind = 0;
        minfam = -1;
        lettre = sign_garde(1+(i-1)*7*unite:i*7*unite);
        for j = 1:10
            norma = norm(lettre - A(j,:));
            if norma < minval
               minval = norma;
               minind = j;
               minfam = 0;
            end
            normb = norm(lettre - B(j,:));
            if normb < minval
               minval = normb;
               minind = j;
               minfam = 1;
            end
            normc = norm(lettre - C(j,:));
            if normc < minval
               minval = normc;
               minind = j;
               minfam = 2;
            end 
        end
        tab(i+1) = minind-1;
        famille(i) = minfam;
    end
    
    %determination du premier chiffre
    minind = -1;
    minval = 999;
    for i=1:10
        n = norm(premier(i,:)-famille);
        if n< minval
            minval = n;
            minind = i;
        end
    end
    tab(1)=minind-1;
    %On passe la garde central
    sign_garde_final = sign_garde((6*7+5)*unite+1:end);
    
    for i = 1:6
        minval = 999;
        minind = 0;
        lettre = sign_garde_final(1+(i-1)*7*unite:i*7*unite);
        for j = 1:10
            norma = norm(lettre - A(j,:));
            if norma < minval
               minval = norma;
               minind = j;
            end
            normb = norm(lettre - B(j,:));
            if normb < minval
               minval = normb;
               minind = j;
            end
            normc = norm(lettre - C(j,:));
            if normc < minval
               minval = normc;
               minind = j;
            end
        end
        tab(i+7) = minind-1;
    end
    
    tab(13) = 10 - mod(sum(tab(1:2:11)) + 3*sum(tab(2:2:12)),10);

end