function tab = iden(sign,unite)

    
    %type de message
    A1 = [...
        [0,0,0,1,1,0,1];...
        [0,0,1,1,0,0,1];...
        [0,0,1,0,0,1,1];...
        [0,1,1,1,1,0,1];...
        [0,1,0,0,0,1,1];...
        [0,1,1,0,0,0,1];...
        [0,1,0,1,1,1,1];...
        [0,1,1,1,0,1,1];...
        [0,1,1,0,1,1,1];...
        [0,0,0,1,0,1,1] ];
    B1 = [...
        [0,1,0,0,1,1,1];...
        [0,1,1,0,0,1,1];...
        [0,0,1,1,0,1,1];...
        [0,1,0,0,0,0,1];...
        [0,0,1,1,1,0,1];...
        [0,1,1,1,0,0,1];...
        [0,0,0,0,1,0,1];...
        [0,0,1,0,0,0,1];...
        [0,0,0,1,0,0,1];...
        [0,0,1,0,1,1,1] ];
    C1 = [...
        [1,1,1,0,0,1,0];...
        [1,1,0,0,1,1,0];...
        [1,1,0,1,1,0,0];...
        [1,0,0,0,0,1,0];...
        [1,0,1,1,1,0,0];...
        [1,0,0,1,1,1,0];...
        [1,0,1,0,0,0,0];...
        [1,0,0,0,1,0,0];...
        [1,0,0,1,0,0,0];...
        [1,1,1,0,1,0,0] ];
        
    %tableau de determination du premier chiffre
    premier = [...
        [0,0,0,0,0,0];...
        [0,0,1,0,1,1];...
        [0,0,1,1,0,1];...
        [0,0,1,1,1,0];...
        [0,1,0,0,1,1];...
        [0,1,1,0,0,1];...
        [0,1,1,1,0,0];...
        [0,1,0,1,0,1];...
        [0,1,0,1,1,0];...
        [0,1,1,0,1,0] ];
    
    A = double(fairetab(A1,unite));
    B = double(fairetab(B1,unite));
    C = double(fairetab(C1,unite));
    
        
    sign_garde = sign(3*unite+1:end-3*unite); %On enlève les gardes des bords
    tab = zeros(1,13); % tableau de nombre du code barre
    famille = zeros(1,6); % familles des chiffres 2 a 6
    
    for i = 1:6
        minval = 999;
        minind = 0;
        minfam = -1;
        lettre = sign_garde(1+(i-1)*7*unite:i*7*unite);
        for j = 1:10
            my_norm_vecta = my_norm_vect(lettre - A(j,:));
            if my_norm_vecta < minval
               minval = my_norm_vecta;
               minind = j;
               minfam = 0;
            end
            my_norm_vectb = my_norm_vect(lettre - B(j,:));
            if my_norm_vectb < minval
               minval = my_norm_vectb;
               minind = j;
               minfam = 1;
            end
            my_norm_vectc = my_norm_vect(lettre - C(j,:));
            if my_norm_vectc < minval
               minval = my_norm_vectc;
               minind = j;
               minfam = 2;
            end 
        end
        tab(i+1) = minind-1;
        famille(i) = minfam;
    end
    
    %determination du premier chiffre
    minind = -1;
    minval = 999;
    for i=1:10
        n = my_norm_vect(premier(i,:)-famille);
        if n< minval
            minval = n;
            minind = i;
        end
    end
    tab(1)=minind-1;
    %On passe la garde central
    sign_garde_final = sign_garde((6*7+5)*unite+1:end);
    
    for i = 1:6
        minval = 999;
        minind = 0;
        lettre = sign_garde_final(1+(i-1)*7*unite:i*7*unite);
        for j = 1:10
            my_norm_vecta = my_norm_vect(lettre - A(j,:));
            if my_norm_vecta < minval
               minval = my_norm_vecta;
               minind = j;
            end
            my_norm_vectb = my_norm_vect(lettre - B(j,:));
            if my_norm_vectb < minval
               minval = my_norm_vectb;
               minind = j;
            end
            my_norm_vectc = my_norm_vect(lettre - C(j,:));
            if my_norm_vectc < minval
               minval = my_norm_vectc;
               minind = j;
            end
        end
        tab(i+7) = minind-1;
    end
    
    tab(13) = 10 - mod(sum(tab(1:2:11)) + 3*sum(tab(2:2:12)),10);

end